// <auto-generated />
using System;
using FB.SuperSearcher.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FB.SuperSearcher.Data.Migrations
{
    [DbContext(typeof(SearchStatisticDbContext))]
    partial class SearchStatisticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FB.SuperSearcher.Data.Models.SearchDateDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SearchDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SearchTermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SearchTermId");

                    b.ToTable("SearchDates");
                });

            modelBuilder.Entity("FB.SuperSearcher.Data.Models.SearchTermCharactersDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("SearchTermId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SearchTermId");

                    b.ToTable("SearchTermCharacters");
                });

            modelBuilder.Entity("FB.SuperSearcher.Data.Models.SearchTermDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("SearchTerm");

                    b.ToTable("SearchTerms");
                });

            modelBuilder.Entity("FB.SuperSearcher.Data.Models.SearchDateDbModel", b =>
                {
                    b.HasOne("FB.SuperSearcher.Data.Models.SearchTermDbModel", "SearchTerm")
                        .WithMany("SearchDates")
                        .HasForeignKey("SearchTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchTerm");
                });

            modelBuilder.Entity("FB.SuperSearcher.Data.Models.SearchTermCharactersDbModel", b =>
                {
                    b.HasOne("FB.SuperSearcher.Data.Models.SearchTermDbModel", "SearchTerm")
                        .WithMany("Characters")
                        .HasForeignKey("SearchTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchTerm");
                });

            modelBuilder.Entity("FB.SuperSearcher.Data.Models.SearchTermDbModel", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("SearchDates");
                });
#pragma warning restore 612, 618
        }
    }
}
